version: 2

jobs:
  plan-apply:
    working_directory: /tmp/project
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - run:
          command: echo $gcp_cred | cat > sec_gcp.json
      - run:
          name: terraform init & plan
          command: |
            terraform init #-input=false
            terraform plan
           # terraform plan -out tfapply -var-file variables.tfvars
      - persist_to_workspace:
          root: .
          paths:
            - .
workflows:
  version: 2
  build_and_deploy_to_cloudrun:
    jobs:
      - plan-apply
